<?php
/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function entity_ref_tab_formatter_theme() {
  return array(
    'entity_ref_tab_formatter' => array(
      'variables' => array('tabs' => NULL),
      'template' => 'entity-ref-tab-formatter',
    ),
    'entity_ref_accordion_formatter' => array(
      'variables' => array('tabs' => NULL),
      'template' => 'entity-ref-accordion-formatter',
    ),
  );
}
