hsts.settings:
  type: config_object
  label: 'HSTS settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable HSTS'
    max_age:
      type: integer
      label: 'Max age'
    subdomains:
      type: boolean
      label: 'Include subdomains'
