# Schema for the configuration of the Range (integer) field type.

field.storage_settings.range_integer:
  type: mapping
  label: 'Range (integer) settings'

field.field_settings.range_integer:
  type: mapping
  label: 'Range (integer) settings'
  mapping:
    min:
      type: integer
      label: 'Minimum'
    max:
      type: integer
      label: 'Maximum'
    from:
      type: mapping
      label: 'FROM'
      mapping:
        prefix:
          type: label
          label: 'Prefix'
        suffix:
          type: label
          label: 'Suffix'
    to:
      type: mapping
      label: 'TO'
      mapping:
        prefix:
          type: label
          label: 'Prefix'
        suffix:
          type: label
          label: 'Suffix'

field.value.range_integer:
  type: mapping
  label: 'Default value'
  mapping:
    from:
      type: integer
      label: 'FROM'
    to:
      type: integer
      label: 'TO'

# Schema for the configuration of the Range (decimal) field type.

field.storage_settings.range_decimal:
  type: mapping
  label: 'Range (decimal) settings'
  mapping:
    precision:
      type: integer
      label: 'Precision'
    scale:
      type: integer
      label: 'Scale'

field.field_settings.range_decimal:
  type: mapping
  label: 'Range (decimal) settings'
  mapping:
    min:
      type: float
      label: 'Minimum'
    max:
      type: float
      label: 'Maximum'
    from:
      type: mapping
      label: 'FROM'
      mapping:
        prefix:
          type: label
          label: 'Prefix'
        suffix:
          type: label
          label: 'Suffix'
    to:
      type: mapping
      label: 'TO'
      mapping:
        prefix:
          type: label
          label: 'Prefix'
        suffix:
          type: label
          label: 'Suffix'

field.value.range_decimal:
  type: mapping
  label: 'Default value'
  mapping:
    from:
      type: float
      label: 'FROM'
    to:
      type: float
      label: 'TO'

# Schema for the configuration of the Range (decimal) field type.

field.storage_settings.range_float:
  type: mapping
  label: 'Range (float) settings'

field.field_settings.range_float:
  type: mapping
  label: 'Range (float) settings'
  mapping:
    min:
      type: float
      label: 'Minimum'
    max:
      type: float
      label: 'Maximum'
    from:
      type: mapping
      label: 'FROM'
      mapping:
        prefix:
          type: label
          label: 'Prefix'
        suffix:
          type: label
          label: 'Suffix'
    to:
      type: mapping
      label: 'TO'
      mapping:
        prefix:
          type: label
          label: 'Prefix'
        suffix:
          type: label
          label: 'Suffix'

field.value.range_float:
  type: mapping
  label: 'Default value'
  mapping:
    from:
      type: float
      label: 'FROM'
    to:
      type: float
      label: 'TO'

field.formatter.settings.range_integer:
  type: mapping
  label: 'Range integer display format settings'
  mapping:
    range_separator:
      type: string
      label: 'Range separator'
    thousand_separator:
      type: string
      label: 'Thousand marker'
    range_combine:
      type: boolean
      label: 'Combine equivalent values'
    from_prefix_suffix:
      type: boolean
      label: 'Display FROM value prefix and suffix'
    to_prefix_suffix:
      type: boolean
      label: 'Display TO value prefix and suffix'

field.formatter.settings.range_decimal:
  type: mapping
  label: 'Range decimal display format settings'
  mapping:
    range_separator:
      type: string
      label: 'Range separator'
    thousand_separator:
      type: string
      label: 'Thousand marker'
    decimal_separator:
      type: string
      label: 'Decimal marker'
    scale:
      type: integer
      label: 'Scale'
    range_combine:
      type: boolean
      label: 'Combine equivalent values'
    from_prefix_suffix:
      type: boolean
      label: 'Display FROM value prefix and suffix'
    to_prefix_suffix:
      type: boolean
      label: 'Display TO value prefix and suffix'

field.formatter.settings.range_unformatted:
  type: mapping
  label: 'Range unformatted display format settings'
  mapping:
    range_separator:
      type: string
      label: 'Range separator'
