<?php

/**
 * @file
 * Imagefield Slideshow module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function imagefield_slideshow_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the imagefield slideshow module.
    case 'help.page.imagefield_slideshow':
      $output = '';
      $output .= '<h3>' . t('Imagefield Slideshow') . '</h3>';
      $output .= '<p>' . t('Imagefield Slideshow will provide a field formatter, so that the images uploaded for an image field would be rendered as a Slider.') . '</p>';
      $output .= '<p>' . t('Visit module page for more details.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function imagefield_slideshow_theme() {
  return [
    'imagefield_slideshow' => [
      'variables' => [
        'url' => NULL,
        'effect' => NULL,
        'pause' => NULL,
        'prev_next' => NULL,
        'speed' => NULL,
        'timeout' => NULL,
        'pager' => NULL,
      ],
    ],
  ];
}
